name: "lf-c-unthreaded"
validation_alias: "lf-c"
prepare: ["mkdir", "src"]
copy: ["cp", "-r", "${benchmark.targets.lf-c.copy_sources}", "${bench_path}/C/Savina/src/include", "src"]
gen: ["cog", "-r", "${args:benchmark.targets.lf-c.gen_args}",
      "-D", "numIterations=${iterations}",
      "-D", "threading=False",
      "src/${benchmark.targets.lf-c.lf_file}"]
compile: ["${lf_path}/bin/lfc-dev", "src/${benchmark.targets.lf-c.lf_file}"]
run: ["bin/${benchmark.targets.lf-c.binary}"]
parser:
  _target_: "parser.parse_lfc_output"
