iterations: 12
threads: null
timeout: 1200
savina_path: "${oc.env:SAVINA_PATH}"
lf_path: "${oc.env:LF_PATH}"
bench_path: "${oc.env:LF_BENCHMARKS_PATH}"
continue_on_error: False
test_mode: False

# keep the chdir behaviour of hydra<1.2.0
hydra:
  job:
    chdir: True

defaults:
  - benchmark: ???
  - target: ???
  - _self_
