# Main workflow for testing the Lingua Franca benchmarks.
name: CI

on:
  # Trigger this workflow on push events, but only on main.
  push:
    branches:
      - main
  # Trigger this workflow also on pull_request events
  pull_request:

jobs:
  # Test the C benchmarks.
  c-benchmark-tests:
    uses: ./.github/workflows/benchmark-tests.yml
    with:
      target: 'C'
  cpp-benchmark-tests:
    uses: ./.github/workflows/benchmark-tests.yml
    with:
      target: 'Cpp'
  rs-benchmark-tests:
    uses: ./.github/workflows/benchmark-tests.yml
    with:
      target: 'Rust'
  ts-benchmark-tests:
    uses: ./.github/workflows/benchmark-tests.yml
    with:
      target: 'TS'

